### ISSUE TITLE
Why all files are copied to destination folder?

### ISSUE THREAD

**Issue by zemd** [g13013/broccoli-compass#39]
I have next configuration 

``` js
const rootDir = 'src';

const styles = pickFiles(rootDir, {
  srcDir: 'styles'
});

const compassTree = compileSass(styles, {
  outputStyle: 'expanded',
  sassDir: '.',
  cssDir: '.',
  compassCommand: 'bundle exec compass',
  imagesDir: path.join(__dirname, '/src/images'),
  config: path.join(__dirname, '/compass.rb')
});

module.exports = compassTree;
```

after compilation `broccoli build ./static/styles` I have next folder structure

![image](https://cloud.githubusercontent.com/assets/433708/9566442/52480198-4f0e-11e5-84fd-35fb5c13dd20.png)

Why does it happen? Why do all scss files are copied? If I try to compile only one specific file (adding files: ['application.scss'] to configuration) I have an error: `Individual stylesheets must be in the sass directory.`

I'm using:
compass v1.0.3
sass v3.4.18
ruby v2.2.2p95
broccoli v0.16.7
node v0.12.0

ps I've working also with middleman and using the same compass and sass versions and it works great, so I think it is not versions problems.

**Comment by g13013** [comment]
Hi @zemd and sorry for the delay:

there is a `cleanOutput` in order to do that, see the list of options: https://github.com/g13013/broccoli-compass#plugin-options

The only reason is performance, one of the challenges I faced is to keep the source directory and destination clean. because if we compile in source directory it becomes unclean and can trigger other compilation cycles, also for large projects traversing a tree after a compilation to pickup all the generated css can cost some time.

**Comment by zemd** [comment]
before I posted the issue tried to play with cleanOut option, but it didn't help, and also triggered some error that I didn't figure out with. after that found that broccoli-ruby-sass makes less requirements to achieve results.

> also for large projects traversing a tree after a compilation to pickup all the generated css can cost some time

but cleaning all these files also takes some time and makes error-prone case when it can be removed something that shouldn't. I have many-many "scss-blocks" in my project and compilation with compass hasn't enforced me to wait, also I tried broccoli-ruby-sass and it also pretty fast. I do not see how it can help to perform building sass.

**Comment by g13013** [comment]
Which OS do you use ? What are the errors you got ? and also what do you suggest ?

**Comment by zemd** [comment]
I am using os x. I will post an error in the next comment, because currently I'm using another plugin and need to modify build process. 

I suggest to copy compilation output only, no need to copy all the scss files and then clean them out. Or compile directly to destination folder as it was done in broccoli-ruby-sass for example

**Comment by g13013** [comment]
@zemd 
    `I suggest to copy compilation output only`

if `cleanOutput` is `true`, the plugin simply returns the compilation folder, if it's `false` it will only symlink to the destination folder all generated CSS files and the fonts/images they refer to.  the only exception is on Windows, where it copies instead of symlinking.

`cleanOutput` should work for you, what is the error ?

**Comment by g13013** [comment]
@zemd Is the problem persist ?

**Comment by g13013** [comment]
I close for now, please reopen it if you think it still relevant !
